[phases.setup]
nixPkgs = ['php84', 'php84Extensions.pdo', 'php84Extensions.pdo_mysql', 'nodejs', 'npm']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci', 'npm run build']

[phases.build]
cmds = ['chmod +x railway/*.sh']

[start]
cmd = 'bash railway/init-app.sh && php artisan serve --host=0.0.0.0 --port=$PORT'
