[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql', 'php83Extensions.openssl', 'php83Packages.composer', 'nodejs']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci', 'npm run build']

[phases.build]
cmds = ['chmod +x railway/*.sh']

[start]
cmd = 'bash railway/init-app.sh && php artisan serve --host=0.0.0.0 --port=$PORT'
