services:
  - type: web
    name: cbmproject
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: cbmproject-redis
          property: connectionString

  - type: redis
    name: cbmproject-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []
